# PAGE D'ACCUEIL
acme_site_home:
    path: /
    defaults: { _controller: "AcmeGroupSiteBundle:Site:index" }

acme_site_accueil:
    path: /rayon-de-soleil
    defaults: { _controller: "AcmeGroupSiteBundle:Site:index" }


## PAGES CATEGORISÉES
acme_site_pageweb:
    path: /page-{categorieSlug}/{pagewebSlug}/{pagedata}
    defaults: { _controller: "AcmeGroupSiteBundle:Site:pageweb", categorieSlug: "web", pagewebSlug: null, pagedata: null }

acme_site_events:
    path: /evenements/liste/{typeEvent}/{categorieSlug}
    defaults: { _controller: "AcmeGroupSiteBundle:Site:events", categorieSlug: null }

acme_site_detailEvent:
    path: /evenement/detail/{eventSlug}/{categorieSlug}
    defaults: { _controller: "AcmeGroupSiteBundle:Site:detailEvent", categorieSlug: null }

acme_site_valeurs:
    path: /categorie/valeurs/{categorieSlug}
    defaults: { _controller: "AcmeGroupSiteBundle:Site:valeurs", categorieSlug: null }

acme_site_equipe:
    path: /equipe/{categorieSlug}
    defaults: { _controller: "AcmeGroupSiteBundle:Site:equipe", categorieSlug: null }

acme_site_mediapresse:
    path: /media-presse/{slugarticle}/{categorieSlug}
    defaults: { _controller: "AcmeGroupSiteBundle:Site:mediapresse", slugarticle: "liste", categorieSlug: null }

acme_site_agenda:
    path: /agenda/{date}/{categorieSlug}
    defaults: { _controller: "AcmeGroupSiteBundle:Site:agenda", date: "liste", categorieSlug: null }


## FLUX
acme_rss_getrss:
    path: /flux.rss
    defaults: { _controller: "AcmeGroupSiteBundle:Site:getRss" }
