<?php

namespace AcmeGroup\LaboBundle\Entity;

// use AcmeGroup\LaboBundle\Entity\baseRepository;
use labo\Bundle\TestmanuBundle\Entity\categorieRepository as categorieBaseRepo;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends categorieBaseRepo {

	/**
	* defaultMenu
	* Renvoie l'instance de la version par défaut (ou null)
	*/
	public function defaultMenu($nommenu = null) {
		if($nommenu === null) $nommenu = "menu_01";
		$qb = $this->createQueryBuilder('element')
			->where('element.nom = :nom')
			->setParameter('nom', $nommenu)
		;
		$qb = $this->withVersion($qb);
		$qb = $this->defaultStatut($qb);
		return $qb->getQuery()->getOneOrNullResult();
	}

}