<?php

namespace AcmeGroup\LaboBundle\Entity;

// use AcmeGroup\LaboBundle\Entity\baseRepository;
use labo\Bundle\TestmanuBundle\Entity\laboBaseRepository;
// use labo\Bundle\TestmanuBundle\Entity\typeMembreRepository as typeMembreBaseRepo;

/**
 * typeMembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeMembreRepository extends laboBaseRepository {


}